version: '3'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DD_AGENT_HOST=datadog-agent          # Talks to agent container by name
      - DD_TRACE_AGENT_PORT=8136             # Custom APM port
      - DD_SERVICE=mern-notes-backend
      - DD_ENV=dev
      - DD_VERSION=1.0
    volumes:
      - ./server:/app
    depends_on:
      - datadog-agent

  frontend:
    build: ./client/client
    ports:
      - "3000:3000"
    volumes:
      - ./client/client:/app
    depends_on:
      - backend

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    environment:
      - DD_API_KEY=<REPLACE WITH API KEY>
      - DD_SITE=datadoghq.com
      - DD_APM_ENABLED=true
      - DD_APM_RECEIVER_PORT=8136            # Agent listens on 8136
      - DD_LOGS_ENABLED=true
    ports:
      - "8136:8136"                          # Exposes port to other containers (and host, if needed)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
